version: '3'

services:
  app:
    build:
      context:
        ./
    links:
      - mysql
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
